type AllCarModelType = {
  [key: string]: string[]
}

export const carFuel = ["Essence", "Diesel", "Electrique", "Hybride"]
export const carEngine = ["Automatique", "Manuel", "Hybride"]
export const carType = [
  "SUV",
  "Berline",
  "Break",
  "Coupe",
  "Citadine",
  "Sport",
  "Cabriolet",
  "Espace",
  "Pick-up",
]
export const numberOfSeat = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
]

export const carYear = [
  "2025",
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
  "Avant 2000",
]
export const allCarBrand = [
  "Volkswagen",
  "Audi",
  "Mercedes",
  "BMW",
  "Peugeot",
  "Citroen",
  "Renault",
  "Lamborghini",
  "Ferrari",
  "Maserati",
  "Porsche",
  "Smart",
  "Mini",
  "Abarth",
  "Toyota",
  "Alfa Romeo",
  "DS",
  "Aston Martin",
  "Bentley",
  "Bugatti",
  "Fiat",
  "Ford",
  "Hummer",
  "Jeep",
  "Kia",
  "Land Rover",
  "Lexus",
  "MG",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Rolls-Royce",
  "Seat",
  "Skoda",
  "Tesla",
  "Volvo",
  "Autre",
]
export const carModels = { Audi: ["hello"] }
export const allCarModel: AllCarModelType = {
  Audi: [
    "S1",
    "S3",
    "S3 Sportback",
    "S3 Berline",
    "S4",
    "S4 Avant",
    "S4 Berline",
    "S5",
    "S6",
    "S6 Avant",
    "S6 Berline",
    "S7 Sportback",
    "SQ2",
    "SQ5",
    "SQ7",
    "SQ8",
    "TTS Coupe",
    "TTS Roadster",
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
    "TT",
    "R8",
    "R8 Coupe",
    "R8 Spyder",
    "RS 3 Sportback",
    "RS 3 Berline",
    "RS 4 Avant",
    "RS 5 Sportback",
    "RS 5 Coupe",
    "RS Avant",
    "RS 7 Sportback",
    "RS Q3",
    "RS Q3 Sportback",
    "RS Q8",
    "TT RS Coupé",
    "TT RS Roadster",
    "Q4 e-tron",
    "Q8 e-tron",
    "e-tron",
    "e-tron GT",
    "Autre",
  ],
  "Alfa Romeo": [
    "Stelvio",
    "Stelvio Quadrifoglio",
    "Giulia",
    "Giulia Quadrifoglio",
    "New Giulietta",
    "Mito",
    "4C",
    "4C Spider",
    "Tonale",
    "Autre",
  ],
  DS: [
    "DS 3",
    "DS 3 Crossback",
    "DS 4",
    "DS 7",
    "DS 7 Crossback",
    "DS9",
    "Autre",
  ],
  Abarth: [
    "124 spider",
    "595",
    "695 Biposto XSR",
    "695 Rivale",
    "695 Maserati Edition",
    "695 Asseto Corse",
    "500 Asseto Corse",
    "500 R3T",
    "Autre",
  ],
  Citroen: [
    "New C3",
    "New C4",
    "C5 AIRCROSS",
    "C3 AIRCROSS",
    "BERLINGO",
    "C1",
    "C4",
    "C4 X",
    "C5 X",
    "C5",
    "GRAND C4 PICASSO",
    "C-ZERO",
    "C3 PICASSO",
    "C4 CACTUS",
    "JUMPY",
    "JUMPER",
    "Autre",
  ],
  Fiat: [
    "500",
    "500c",
    "Tipo",
    "Panda",
    "500L",
    "500X",
    "Freemont",
    "Qubo",
    "Doblo",
    "Autre",
  ],
  Jeep: ["Renegade", "Wrangler", "Cherokee", "Compass", "Autre"],
  Opel: ["Astra", "Corsa", "Crossland", "Grandland", "Mokka", "Autre"],
  Peugeot: [
    "208",
    "308 GTi",
    "5008",
    "3008",
    "2008",
    "208 GTi",
    "108",
    "Traveller",
    "Partner Teepe",
    "Expert",
    "Autre",
  ],
  "Aston Martin": [
    "VALHALA",
    "DBX",
    "VANTAGE",
    "DB11",
    "DBS",
    "VALKYRIE",
    "Autre",
  ],
  Bentley: ["Autres"],
  BMW: [
    "i4",
    "i5",
    "i7",
    "iX",
    "iX1",
    "iX3",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "X2 M35i",
    "X3 M Competition",
    "X4 M Competition",
    "iX M60",
    "X5 M Competition",
    "X6 M Competition",
    "X7 M60i xDrive",
    "Série 1",
    "Série 2 Active Tourer",
    "Série 2 Coupé",
    "Série 2 Gran Coupé",
    "Série 3 Berline",
    "Série 3 Touring",
    "Série 4 Gran Coupé",
    "Série 4 Coupé",
    "Série 4 Cabriolet",
    "Série 5 Berline",
    "Série 5 Touring",
    "Série 7",
    "Série 8 Coupé",
    "Série 8 Gran Coupé",
    "Série 8 Cabriolet",
    "M135i xDrive",
    "XM",
    "M3",
    "M3 Competition Berline",
    "M5 Competition Berline",
    "M2 Coupé",
    "M2",
    "M235i Xdrive Gran Coupé",
    "M4",
    "M",
    "M4 Competition Cabriolet",
    "M8 Competition cabriolet",
    "Z4",
    "Z4 M40i",
    "Autre",
  ],
  Ferrari: ["F12", "Autres"],
  Ford: ["Autres"],
  Hummer: ["Autres"],
  Lamborghini: [
    "Huracan",
    "Revuelto",
    "Urus",
    "Aventador",
    "Centenario",
    "Sian",
    "Veneno",
    "Autres",
  ],
  Kia: ["Autres"],
  Lexus: ["Autres"],
  Maserati: ["Autres"],
  Mercedes: [
    "Classe A",
    "Classe B",
    "Classe C",
    "Classe E",
    "Classe G",
    "Classe S",
    "Classe T",
    "Classe V",
    "Classe X",
    "Classe Cls",
    "Cla",
    "Gla",
    "Glb",
    "Glc",
    "Glc Coupe",
    "Gle",
    "Gle Coupe",
    "Gls",
    "AMG C63",
    "AMG C63 S",
    "AMG CLA 35",
    "AMG CLA 45",
    "AMG C63 Black Series",
    "AMG CLS 63",
    "AMG CLK 63 Black Series",
    "AMG CLS 53",
    "AMG C43",
    "AMG E43",
    "AMG E53",
    "AMG E63 S",
    "AMG E63",
    "AMG S65",
    "AMG S63",
    "AMG SL",
    "AMG SLC 43",
    "AMG SLS",
    "AMG SLk 55",
    "AMG SL 63",
    "AMG SL 65",
    "AMG SLS GT",
    "AMG A45",
    "AMG A45 S",
    "AMG G 55",
    "AMG G 63",
    "AMG G 65",
    "AMG GT",
    "AMG GT 63 S",
    "AMG GT R",
    "AMG GT R Pro",
    "AMG GT S",
    "AMG GT C",
    "AMG GLS 63",
    "AMG GLS 65",
    "AMG GLA 45",
    "AMG GLC 43",
    "AMG GLC 63",
    "AMG GLC 63 S",
    "AMG GLE 43",
    "AMG GLE 53",
    "AMG GLE 63",
    "AMG GLE 63 S Coupe",
    "AMG GLK 55",
    "AMG GT 4-Door",
    "AMG Black Series",
    "AMG GT Black Series",
    "AMG ML 63",
    "AMG One",
    "AMG Project One",
    "SLR McLaren",
    "SLS Electric Drive ",
    "Vito",
    "Sprinter",
    "Eqa",
    "Eqb",
    "Eqs",
    "Eqs Suv",
    "Eqt",
    "Eqv",
    "Sl",
    "Slc",
    "Citan",
    "Autre",
  ],
  MG: ["Autres"],
  Mini: [
    "Countryman",
    "Mini",
    "Mini Cabriolet",
    "Mini Clubman",
    "Mini Paceman",
    "Mini Crossman",
    "Mini Crossover",
    "Autre",
  ],
  Mitsubishi: ["Autres"],
  Nissan: ["Autres"],
  Renault: [
    "Arkana",
    "Austral",
    "Clio",
    "Clio 4",
    "Clio 5",
    "Captur",
    "Espace",
    " Gran Scenic",
    "Express van",
    "Kangoo",
    "Kadjar",
    "Kangoo van",
    "Kangoo Express",
    "Koleos",
    "Megane",
    "Scenic",
    "Master",
    "Talisman",
    "Trafic",
    "Twingo",
    "Zoe",
    "Twizy",
    "Triber",
    "Autre",
  ],
  Porsche: ["718", "911", "Macan", "Panamera", "Cayenne", "Taycan", "Autre"],
  "Rolls-Royce": ["Phantom", "Dawn", "Spectre", "Autre"],
  Seat: ["Ateca", "Leon", "Ibiza", "Arona", "Tarraco", "Autre"],
  Skoda: [
    "Fabia",
    "Scala",
    "Kamiq",
    "Octavia Combi",
    "Karoq",
    "Kodiaq",
    "Enyaq iV",
    "Enyac Coupé iV",
    "Superb",
    "Superb Combi",
    "Autre",
  ],
  Toyota: [
    "Auris",
    "Avensis",
    "Aygo",
    "Aygo X",
    "Bz4x",
    "C-hr",
    "Camry",
    "Corolla",
    "Corolla Cross",
    "Gr 86",
    "Highlander",
    "Hilux",
    "Land Cruiser",
    "Mirai",
    "Prius",
    "Proace",
    "Proace City",
    "Proace Verso",
    "Rav 4",
    "Supra",
    "Yaris",
    "Yaris Cross",
    "Autre",
  ],
  Smart: ["Fortwo", "Autres"],
  Tesla: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y", "Autre"],
  Volkswagen: [
    "Golf 5",
    "Golf 6",
    "Golf 6 Gti",
    "Golf 7",
    "Golf 7 Gti",
    "Golf 7 Gtd",
    "Golf 8",
    "Golf 8 Gti",
    "Golf 8 Gtd",
    "Golf 7 R",
    "Golf 8 R",
    "Golf 6 R",
    "Polo",
    "Polo Gtd",
    "Polo Gti",
    "Polo R",
    "T-cross",
    "T-roc",
    "T-roc R",
    "Taigo",
    "Tiguan",
    "Tiguan R",
    "Touareg",
    "Touareg R",
    "Autre",
  ],
  Volvo: ["Autres"],
  Bugatti: ["Autres"],
  "Land Rover": ["Autres"],
}

export const PostalCode = [
  "95",
  "94",
  "93",
  "92",
  "91",
  "90",
  "89",
  "88",
  "87",
  "85",
  "86",
  "84",
  "83",
  "82",
  "81",
  "80",
  "79",
  "78",
  "77",
  "76",
  "75",
  "74",
  "73",
  "72",
  "71",
  "70",
  "69",
  "68",
  "67",
  "66",
  "65",
  "64",
  "63",
  "62",
  "61",
  "61",
  "60",
  "59",
  "58",
  "57",
  "56",
  "55",
  "54",
  "53",
  "52",
  "51",
  "50",
  "49",
  "48",
  "47",
  "46",
  "45",
  "44",
  "43",
  "42",
  "41",
  "40",
  "39",
  "38",
  "37",
  "36",
  "35",
  "34",
  "33",
  "32",
  "31",
  "30",
  "29",
  "28",
  "27",
  "26",
  "25",
  "24",
  "23",
  "22",
  "21",
  "20",
  "19",
  "18",
  "17",
  "16",
  "15",
  "14",
  "13",
  "12",
  "11",
  "10",
  "09",
  "08",
  "07",
  "06",
  "05",
  "04",
  "03",
  "02",
  "01",
]
